export const BlogData = [
	{
		title: "React Important concepts you should know",
		author: "Mojodev",
		date: "10 May 2021",
		reactions_count: "8",
		comments_count: "6",
	},
	{
		title: "A brief introduction to Dart",
		author: "Denyse",
		date: "21 May 2021",
		reactions_count: "20",
		comments_count: "4",
	},
	{
		title: "Want free Wordpress Hosting",
		author: "GoodBoyKs",
		date: "21 May 2021",
		reactions_count: "6",
		comments_count: "1",
	},
	{
		title: "Serverless Application is not as secure as you might think!",
		author: "SmartScanner",
		date: "19 May 2021",
		reactions_count: "7",
		comments_count: "3",
	},
	{
		title: "React Important concepts you should know",
		author: "Mojodev",
		date: "10 May 2021",
		reactions_count: "8",
		comments_count: "6",
	},
	{
		title: "A brief introduction to Dart",
		author: "Denyse",
		date: "21 May 2021",
		reactions_count: "20",
		comments_count: "4",
	},
	{
		title: "Want free Wordpress Hosting",
		author: "GoodBoyKs",
		date: "21 May 2021",
		reactions_count: "6",
		comments_count: "1",
	},
	{
		title: "Serverless Application is not as secure as you might think!",
		author: "SmartScanner",
		date: "19 May 2021",
		reactions_count: "7",
		comments_count: "3",
	},
];
