export const CoursesData = [
	{
		id: 1,
		user_id: 1,
		school_id: 1,
		title: "Coding",
		level: 1,
		parent_id: 0,
		ordering: 0,
		description: null,
		rating_sum: 0,
		rated_user: 0,
		video_count: -73,
		total_time: 0,
		num_topics: 13,
		image_url: "https://api.beyondexams.org/course/images/1624634100.png",
		slug: "development-48c97",
		total_views: 0,
		num_actual_topics: 15,
		course_level: null,
		type: 0,
		visibility: 1,
		created_at: "2021-06-06 12:48:05",
		updated_at: "2022-05-19 11:50:38",
		creator: {
			id: 1,
			name: "BeyondExams",
			avatar:
				"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
			slug: "beyondexams-2af4e",
		},
		courses: [
			{
				id: 14,
				user_id: 1,
				school_id: 1,
				title: "Web Development",
				level: 2,
				parent_id: 1,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 216,
				total_time: 0,
				num_topics: 27,
				image_url: "https://i.ytimg.com/vi/jO7PiCbVAXA/mqdefault.jpg",
				slug: "web-development-9460e",
				total_views: 0,
				num_actual_topics: 69,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-05-17 15:39:15",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
				courses: [
					{
						id: 148,
						user_id: 1,
						school_id: 1,
						title: "JavaScript",
						level: 3,
						parent_id: 14,
						ordering: 2,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 96,
						total_time: 0,
						num_topics: 5,
						image_url: "https://i.ytimg.com/vi/z4-8wMSPJyI/mqdefault.jpg",
						slug: null,
						total_views: 0,
						num_actual_topics: 6,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-04-29 20:05:46",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
					{
						id: 149,
						user_id: 1,
						school_id: 1,
						title: "React",
						level: 3,
						parent_id: 14,
						ordering: 3,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 208,
						total_time: 0,
						num_topics: 5,
						image_url: "https://i.ytimg.com/vi/RUku45vpSDU/mqdefault.jpg",
						slug: null,
						total_views: 0,
						num_actual_topics: 4,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-05-17 15:39:15",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
					{
						id: 150,
						user_id: 1,
						school_id: 1,
						title: "CSS",
						level: 3,
						parent_id: 14,
						ordering: 4,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 32,
						total_time: 0,
						num_topics: 1,
						image_url: null,
						slug: null,
						total_views: 0,
						num_actual_topics: 1,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-03-12 15:43:50",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
					{
						id: 151,
						user_id: 1,
						school_id: 1,
						title: "Angular",
						level: 3,
						parent_id: 14,
						ordering: 5,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 165,
						total_time: 0,
						num_topics: 3,
						image_url: "https://i.ytimg.com/vi/dlVVYmntDnE/mqdefault.jpg",
						slug: null,
						total_views: 0,
						num_actual_topics: 3,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-02-07 17:42:48",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
					{
						id: 152,
						user_id: 1,
						school_id: 1,
						title: "Django",
						level: 3,
						parent_id: 14,
						ordering: 6,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 100,
						total_time: 0,
						num_topics: 4,
						image_url: "https://i.ytimg.com/vi/kt3ZtW9MXhw/mqdefault.jpg",
						slug: null,
						total_views: 0,
						num_actual_topics: 4,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-02-07 17:42:48",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
					{
						id: 153,
						user_id: 1,
						school_id: 1,
						title: "PHP",
						level: 3,
						parent_id: 14,
						ordering: 7,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 59,
						total_time: 0,
						num_topics: 2,
						image_url: "https://i.ytimg.com/vi/bt4znmLQCZ8/mqdefault.jpg",
						slug: null,
						total_views: 0,
						num_actual_topics: 2,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-02-07 17:42:48",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
					{
						id: 154,
						user_id: 1,
						school_id: 1,
						title: "Node.Js",
						level: 3,
						parent_id: 14,
						ordering: 8,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 110,
						total_time: 0,
						num_topics: 4,
						image_url: "https://i.ytimg.com/vi/yXEesONd_54/mqdefault.jpg",
						slug: null,
						total_views: 0,
						num_actual_topics: 4,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-02-07 17:42:48",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
					{
						id: 155,
						user_id: 1,
						school_id: 1,
						title: "WordPress",
						level: 3,
						parent_id: 14,
						ordering: 9,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 104,
						total_time: 0,
						num_topics: 5,
						image_url: "https://i.ytimg.com/vi/PQaB0HDdTTg/mqdefault.jpg",
						slug: null,
						total_views: 0,
						num_actual_topics: 5,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-04-13 15:32:21",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
					{
						id: 147,
						user_id: 1,
						school_id: 1,
						title: "Chrome Extensions",
						level: 3,
						parent_id: 14,
						ordering: 10,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 9,
						total_time: 0,
						num_topics: 2,
						image_url: "https://i.ytimg.com/vi/_Ii1-OWaTlk/mqdefault.jpg",
						slug: "chrome-extensions-a87c2",
						total_views: 0,
						num_actual_topics: 2,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-02-07 17:42:48",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
					{
						id: 157,
						user_id: 1,
						school_id: 1,
						title: "Python",
						level: 3,
						parent_id: 14,
						ordering: 11,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 213,
						total_time: 0,
						num_topics: 6,
						image_url: "https://i.ytimg.com/vi/XyyMjKOqyOk/mqdefault.jpg",
						slug: null,
						total_views: 0,
						num_actual_topics: 6,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-02-07 17:42:48",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
					{
						id: 162,
						user_id: 1,
						school_id: 1,
						title: "Front End Web Development",
						level: 3,
						parent_id: 14,
						ordering: 16,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 46,
						total_time: 0,
						num_topics: 3,
						image_url: "https://i.ytimg.com/vi/ANzPM5-lwXc/mqdefault.jpg",
						slug: null,
						total_views: 0,
						num_actual_topics: 2,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-05-19 11:50:26",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
					{
						id: 165,
						user_id: 1,
						school_id: 1,
						title: "Laravel",
						level: 3,
						parent_id: 14,
						ordering: 19,
						description: null,
						rating_sum: 0,
						rated_user: 0,
						video_count: 28,
						total_time: 0,
						num_topics: 1,
						image_url: "https://i.ytimg.com/vi/5fTFHAwWRV4/mqdefault.jpg",
						slug: null,
						total_views: 0,
						num_actual_topics: 1,
						course_level: null,
						type: 0,
						visibility: 1,
						created_at: "2021-06-08 12:48:05",
						updated_at: "2022-02-07 17:42:48",
						creator: {
							id: 1,
							name: "BeyondExams",
							avatar:
								"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
							slug: "beyondexams-2af4e",
						},
					},
				],
			},
			{
				id: 15,
				user_id: 1,
				school_id: 1,
				title: "Data Science",
				level: 2,
				parent_id: 1,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 454,
				total_time: 0,
				num_topics: 10,
				image_url: "https://i.ytimg.com/vi/JL_grPUnXzY/mqdefault.jpg",
				slug: "data-science-d35ad",
				total_views: 0,
				num_actual_topics: 10,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-05-13 11:19:55",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 16,
				user_id: 1,
				school_id: 1,
				title: "Mobile Development",
				level: 2,
				parent_id: 1,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 112,
				total_time: 0,
				num_topics: 3,
				image_url: "https://i.ytimg.com/vi/pTJJsmejUOQ/mqdefault.jpg",
				slug: "mobile-development-74b01",
				total_views: 0,
				num_actual_topics: 3,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-05-19 11:50:38",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 17,
				user_id: 1,
				school_id: 1,
				title: "Programming Languages",
				level: 2,
				parent_id: 1,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 129,
				total_time: 0,
				num_topics: 9,
				image_url: "https://i.ytimg.com/vi/zg9ih6SVACc/mqdefault.jpg",
				slug: "programming-languages-ad20c",
				total_views: 0,
				num_actual_topics: 9,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-05-02 21:04:00",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 19,
				user_id: 1,
				school_id: 1,
				title: "Database Design & Development",
				level: 2,
				parent_id: 1,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 71,
				total_time: 0,
				num_topics: 3,
				image_url: "https://i.ytimg.com/vi/t7FDMLy5rvI/mqdefault.jpg",
				slug: "database-design-&-development-c076d",
				total_views: 0,
				num_actual_topics: 3,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-05-09 14:00:51",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 20,
				user_id: 1,
				school_id: 1,
				title: "Software Testing",
				level: 2,
				parent_id: 1,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 124,
				total_time: 0,
				num_topics: 1,
				image_url: "https://i.ytimg.com/vi/ICbvQzva6lE/mqdefault.jpg",
				slug: "software-testing-c3fd8",
				total_views: 0,
				num_actual_topics: 1,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-01-26 22:15:06",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 21,
				user_id: 1,
				school_id: 1,
				title: "Software Engineering",
				level: 2,
				parent_id: 1,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 93,
				total_time: 0,
				num_topics: 3,
				image_url: "https://i.ytimg.com/vi/X3paOmcrTjQ/mqdefault.jpg",
				slug: "software-engineering-92aa6",
				total_views: 0,
				num_actual_topics: 3,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-02-07 17:42:48",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 23,
				user_id: 1,
				school_id: 1,
				title: "No-Code Development",
				level: 2,
				parent_id: 1,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 13,
				total_time: 0,
				num_topics: 1,
				image_url: "https://i.ytimg.com/vi/Q530u_g2CWE/mqdefault.jpg",
				slug: "no-code-development-25c25",
				total_views: 0,
				num_actual_topics: 1,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-04-21 09:21:31",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
		],
	},
	{
		id: 2,
		user_id: 1,
		school_id: 1,
		title: "Business",
		level: 1,
		parent_id: 0,
		ordering: 0,
		description: null,
		rating_sum: 0,
		rated_user: 0,
		video_count: 372,
		total_time: 0,
		num_topics: 14,
		image_url: "https://api.beyondexams.org/course/images/1624634476.png",
		slug: "business-fcc10",
		total_views: 0,
		num_actual_topics: 22,
		course_level: null,
		type: 0,
		visibility: 1,
		created_at: "2021-06-06 12:48:05",
		updated_at: "2022-05-11 08:48:51",
		creator: {
			id: 1,
			name: "BeyondExams",
			avatar:
				"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
			slug: "beyondexams-2af4e",
		},
		courses: [
			{
				id: 24,
				user_id: 1,
				school_id: 1,
				title: "Entrepreneurship",
				level: 2,
				parent_id: 2,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 38,
				total_time: 0,
				num_topics: 2,
				image_url: "https://i.ytimg.com/vi/jFYTbWXjyVg/mqdefault.jpg",
				slug: "entrepreneurship-1a715",
				total_views: 0,
				num_actual_topics: 2,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-04-26 12:24:35",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 26,
				user_id: 1,
				school_id: 1,
				title: "Management",
				level: 2,
				parent_id: 2,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 65,
				total_time: 0,
				num_topics: 1,
				image_url: "https://i.ytimg.com/vi/mIBccpqUcgY/mqdefault.jpg",
				slug: "management-a6b45",
				total_views: 0,
				num_actual_topics: 1,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-05-11 08:48:51",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 27,
				user_id: 1,
				school_id: 1,
				title: "Sales",
				level: 2,
				parent_id: 2,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 434,
				total_time: 0,
				num_topics: 12,
				image_url: "https://i.ytimg.com/vi/q11TFTK2-FM/mqdefault.jpg",
				slug: "sales-89fa2",
				total_views: 0,
				num_actual_topics: 12,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-02-07 17:42:48",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 28,
				user_id: 1,
				school_id: 1,
				title: "Business Strategy",
				level: 2,
				parent_id: 2,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 232,
				total_time: 0,
				num_topics: 4,
				image_url:
					"https://api.beyondexams.org/category/images/1629275324.jpeg",
				slug: "business-strategy-42baf",
				total_views: 0,
				num_actual_topics: 4,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-02-07 17:17:04",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 33,
				user_id: 1,
				school_id: 1,
				title: "Human Resources",
				level: 2,
				parent_id: 2,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 5,
				total_time: 0,
				num_topics: 2,
				image_url: null,
				slug: "human-resources-fcebd",
				total_views: 0,
				num_actual_topics: 2,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-02-08 10:29:20",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 34,
				user_id: 1,
				school_id: 1,
				title: "Industry",
				level: 2,
				parent_id: 2,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 11,
				total_time: 0,
				num_topics: 1,
				image_url: "https://i.ytimg.com/vi/IUN664s7N-c/mqdefault.jpg",
				slug: "industry-fc927",
				total_views: 0,
				num_actual_topics: 1,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-02-07 17:42:48",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 38,
				user_id: 1,
				school_id: 1,
				title: "Other Business",
				level: 2,
				parent_id: 2,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 8,
				total_time: 0,
				num_topics: 1,
				image_url: "https://i.ytimg.com/vi/7_HKv2wZntg/mqdefault.jpg",
				slug: "other-business-46451",
				total_views: 0,
				num_actual_topics: 1,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-02-07 17:42:48",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
		],
	},
	{
		id: 3,
		user_id: 1,
		school_id: 1,
		title: "Finance & Accounting",
		level: 1,
		parent_id: 0,
		ordering: 0,
		description: null,
		rating_sum: 0,
		rated_user: 0,
		video_count: 0,
		total_time: 0,
		num_topics: 5,
		image_url: "https://api.beyondexams.org/course/images/1624634536.jpg",
		slug: "finance-&-accounting-f7157",
		total_views: 0,
		num_actual_topics: 11,
		course_level: null,
		type: 0,
		visibility: 1,
		created_at: "2021-06-06 12:48:05",
		updated_at: "2022-02-07 17:50:20",
		creator: {
			id: 1,
			name: "BeyondExams",
			avatar:
				"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
			slug: "beyondexams-2af4e",
		},
		courses: [
			{
				id: 39,
				user_id: 1,
				school_id: 1,
				title: "Accounting & Bookkeeping",
				level: 2,
				parent_id: 3,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 118,
				total_time: 0,
				num_topics: 1,
				image_url: "https://i.ytimg.com/vi/k60vUwVIn24/mqdefault_live.jpg",
				slug: "accounting-&-bookkeeping-87111",
				total_views: 0,
				num_actual_topics: 1,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-02-07 17:42:48",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 42,
				user_id: 1,
				school_id: 1,
				title: "Economics",
				level: 2,
				parent_id: 3,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 666,
				total_time: 0,
				num_topics: 14,
				image_url: "https://i.ytimg.com/vi/O-t8-Vq0HO0/mqdefault.jpg",
				slug: "economics-9c98a",
				total_views: 0,
				num_actual_topics: 14,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-02-07 17:42:48",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 43,
				user_id: 1,
				school_id: 1,
				title: "Finance",
				level: 2,
				parent_id: 3,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 758,
				total_time: 0,
				num_topics: 17,
				image_url: "https://i.ytimg.com/vi/1fOt_MQ4UD0/mqdefault.jpg",
				slug: "finance-330da",
				total_views: 0,
				num_actual_topics: 17,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-02-07 17:42:48",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 46,
				user_id: 1,
				school_id: 1,
				title: "Investing & Trading",
				level: 2,
				parent_id: 3,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 38,
				total_time: 0,
				num_topics: 2,
				image_url: "https://i.ytimg.com/vi/AVFnl6oYAQ8/mqdefault.jpg",
				slug: "investing-&-trading-42543",
				total_views: 0,
				num_actual_topics: 2,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-05-19 22:19:43",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 49,
				user_id: 1,
				school_id: 1,
				title: "Other Finance & Accounting",
				level: 2,
				parent_id: 3,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 29,
				total_time: 0,
				num_topics: 1,
				image_url: "https://i.ytimg.com/vi/DP58yBAngsQ/mqdefault.jpg",
				slug: "other-finance-&-accounting-8afe8",
				total_views: 0,
				num_actual_topics: 1,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-02-07 17:42:48",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
		],
	},
	{
		id: 4,
		user_id: 1,
		school_id: 1,
		title: "IT & Software",
		level: 1,
		parent_id: 0,
		ordering: 0,
		description: null,
		rating_sum: 0,
		rated_user: 0,
		video_count: -98,
		total_time: 0,
		num_topics: 6,
		image_url: "https://api.beyondexams.org/course/images/1624634605.jpg",
		slug: "it-&-software-c0ee3",
		total_views: 0,
		num_actual_topics: 5,
		course_level: null,
		type: 0,
		visibility: 1,
		created_at: "2021-06-06 12:48:05",
		updated_at: "2022-05-17 15:39:27",
		creator: {
			id: 1,
			name: "BeyondExams",
			avatar:
				"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
			slug: "beyondexams-2af4e",
		},
		courses: [
			{
				id: 50,
				user_id: 1,
				school_id: 1,
				title: "IT Certification",
				level: 2,
				parent_id: 4,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 15,
				total_time: 0,
				num_topics: 1,
				image_url: "https://i.ytimg.com/vi/bnJ8q99A--k/mqdefault.jpg",
				slug: "it-certification-e193c",
				total_views: 0,
				num_actual_topics: 1,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-02-07 17:42:48",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 51,
				user_id: 1,
				school_id: 1,
				title: "Network & Security",
				level: 2,
				parent_id: 4,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 17,
				total_time: 0,
				num_topics: 1,
				image_url: "https://i.ytimg.com/vi/d-TI_YILdFc/mqdefault.jpg",
				slug: "network-&-security-50970",
				total_views: 0,
				num_actual_topics: 1,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2021-12-16 14:48:01",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 52,
				user_id: 1,
				school_id: 1,
				title: "Hardware",
				level: 2,
				parent_id: 4,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 7,
				total_time: 0,
				num_topics: 1,
				image_url: "https://i.ytimg.com/vi/vyD99T8PqiY/mqdefault.jpg",
				slug: "hardware-3fdf9",
				total_views: 0,
				num_actual_topics: 1,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-05-17 15:39:27",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 53,
				user_id: 1,
				school_id: 1,
				title: "Operating Systems",
				level: 2,
				parent_id: 4,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 4,
				total_time: 0,
				num_topics: 1,
				image_url: "https://i.ytimg.com/vi/PvVQFbZ1y7Q/mqdefault.jpg",
				slug: "operating-systems-6cfac",
				total_views: 0,
				num_actual_topics: 1,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-01-27 03:30:53",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
			{
				id: 54,
				user_id: 1,
				school_id: 1,
				title: "Other IT & Software",
				level: 2,
				parent_id: 4,
				ordering: 0,
				description: null,
				rating_sum: 0,
				rated_user: 0,
				video_count: 25,
				total_time: 0,
				num_topics: 5,
				image_url: "https://i.ytimg.com/vi/MzJv1QWOex0/mqdefault.jpg",
				slug: "other-it-&-software-78c2e",
				total_views: 0,
				num_actual_topics: 6,
				course_level: null,
				type: 0,
				visibility: 1,
				created_at: "2021-06-06 12:48:05",
				updated_at: "2022-05-09 00:26:05",
				creator: {
					id: 1,
					name: "BeyondExams",
					avatar:
						"https://api.beyondexams.org/images/be_logos/instgram%20profile.jpg",
					slug: "beyondexams-2af4e",
				},
			},
		],
	},
];
